common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),


]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from scout import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scout/', include('scout.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

scout/urls.py
from django.urls import path

from . import views

app_name = 'scout'

urlpatterns = [
    path('', views.index, name='index'),
    path('player/<str:player_nick>/',views.scout_report, name='report'),


]

scout/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import  lck_2021_spring_player
from django.db.models import Q





def index(request):
    list=None
    query=None
    test=0
    if 'word' in request.GET:
        query=request.GET.get('word')
        list=lck_2021_spring_player.objects.values().filter(Q(nickname__icontains=query)|Q(team__icontains=query))

    context = {'test':test, 'list':list}
    return render(request, 'scout/index.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- scout CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@900&display=swap" rel="stylesheet">
    <title>LOL scout</title>
    <style>
    p {
      font-family: 'Noto Sans KR', sans-serif;

    }
    p.a{
      font-weight:bold;
      font-size: 23px;
    }
    p.b{
      font-weight:bold;
      font-size: 18px;
    }
    </style>
</head>
<body>

{% include "navbar.html" %}
{% include "side_navbar.html" %}

{% block content %}



{% endblock %}

    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->
<!-- 기본 템플릿 안에 삽입될 내용 Start -->

</div>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'scout:index' %}">2021 LCK scout</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}"></a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/side_navbar.html
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-0 mt-0 mt-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              DWG KIA
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown1">
              <a class="dropdown-item" href="/scout/player/Khan">Khan</a>
              <a class="dropdown-item" href="/scout/player/Canyon">Canyon</a>
              <a class="dropdown-item" href="/scout/player/ShowMaker">ShowMaker</a>
              <a class="dropdown-item" href="/scout/player/Ghost">Ghost</a>
              <a class="dropdown-item" href="/scout/player/BeryL">BeryL</a>

            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Gen.G
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown2">
              <a class="dropdown-item" href="/scout/player/Rascal">Rascal</a>
              <a class="dropdown-item" href="/scout/player/Clid">Clid</a>
              <a class="dropdown-item" href="/scout/player/Flawless">Flawless</a>
              <a class="dropdown-item" href="/scout/player/Bdd">Bdd</a>
              <a class="dropdown-item" href="/scout/player/Karis">Karis</a>
              <a class="dropdown-item" href="/scout/player/Ruler">Ruler</a>
              <a class="dropdown-item" href="/scout/player/Life">Life</a>

            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dragon X
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown3">
              <a class="dropdown-item" href="/scout/player/kingen">kingen</a>
              <a class="dropdown-item" href="/scout/player/Pyosik">Pyosik</a>
              <a class="dropdown-item" href="/scout/player/SOLKA">SOLKA</a>
              <a class="dropdown-item" href="/scout/player/BAO">BAO</a>
              <a class="dropdown-item" href="/scout/player/Becca">Becca</a>

            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hanwha Life Esport
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown4">
              <a class="dropdown-item" href="/scout/player/Morgan">Morgan</a>
              <a class="dropdown-item" href="/scout/player/DuDu">DuDu</a>
              <a class="dropdown-item" href="/scout/player/Arthur">Arthur</a>
              <a class="dropdown-item" href="/scout/player/yoHan">yoHan</a>
              <a class="dropdown-item" href="/scout/player/Chovy">Chovy</a>
              <a class="dropdown-item" href="/scout/player/Deft">Deft</a>
              <a class="dropdown-item" href="/scout/player/Vsta">Vsta</a>
            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown5" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              T1
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown5">
              <a class="dropdown-item" href="/scout/player/Canna">Canna</a>
              <a class="dropdown-item" href="/scout/player/Zeus">Zeus</a>
              <a class="dropdown-item" href="/scout/player/Cuzz">Cuzz</a>
              <a class="dropdown-item" href="/scout/player/Ellim">Ellim</a>
              <a class="dropdown-item" href="/scout/player/Oner">Oner</a>
              <a class="dropdown-item" href="/scout/player/Faker">Faker</a>
              <a class="dropdown-item" href="/scout/player/Clozer">Clozer</a>
              <a class="dropdown-item" href="/scout/player/Teddy">Teddy</a>
              <a class="dropdown-item" href="/scout/player/Gumayusi">Gumayusi</a>
              <a class="dropdown-item" href="/scout/player/Keria">Keria</a>

            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown6" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              KT Rolster
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown6">
              <a class="dropdown-item" href="/scout/player/Doran">Doran</a>
              <a class="dropdown-item" href="/scout/player/GIDEON">GIDEON</a>
              <a class="dropdown-item" href="/scout/player/blank">blank</a>
              <a class="dropdown-item" href="/scout/player/Ucal">Ucal</a>
              <a class="dropdown-item" href="/scout/player/Dove">Dove</a>
              <a class="dropdown-item" href="/scout/player/HyBrid">HyBrid</a>
              <a class="dropdown-item" href="/scout/player/Noah">Noah</a>
              <a class="dropdown-item" href="/scout/player/Zzus">Zzus</a>


            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown7" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              NS REDFORCE
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown7">
              <a class="dropdown-item" href="/scout/player/Rich">Rich</a>
              <a class="dropdown-item" href="/scout/player/Peanut">Peanut</a>
              <a class="dropdown-item" href="/scout/player/Bay">Bay</a>
              <a class="dropdown-item" href="/scout/player/deokdam">deokdam</a>
              <a class="dropdown-item" href="/scout/player/Kellin">Kellin</a>


            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown8" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Live Sandbox
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown8">
              <a class="dropdown-item" href="/scout/player/Summit">Summit</a>
              <a class="dropdown-item" href="/scout/player/OnFleek">OnFleek</a>
              <a class="dropdown-item" href="/scout/player/Croco">Croco</a>
              <a class="dropdown-item" href="/scout/player/FATE">FATE</a>
              <a class="dropdown-item" href="/scout/player/Leo">Leo</a>
              <a class="dropdown-item" href="/scout/player/Route">Route</a>
              <a class="dropdown-item" href="/scout/player/Prince">prince</a>
              <a class="dropdown-item" href="/scout/player/Effort">Effort</a>


            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown9" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Fredit Brion
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown9">
              <a class="dropdown-item" href="/scout/player/Hoya">Hoya</a>
              <a class="dropdown-item" href="/scout/player/UmTi">UmTi</a>
              <a class="dropdown-item" href="/scout/player/Chieftain">Chieftain</a>
              <a class="dropdown-item" href="/scout/player/Lava">Lava</a>
              <a class="dropdown-item" href="/scout/player/Yaharong">Yaharong</a>
              <a class="dropdown-item" href="/scout/player/Hena">Hena</a>
              <a class="dropdown-item" href="/scout/player/Delight">Delight</a>


            </div>

          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown10" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Afreeca Freecs
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown10">
              <a class="dropdown-item" href="/scout/player/Kiin">Kiin</a>
              <a class="dropdown-item" href="/scout/player/Dread">Dread</a>
              <a class="dropdown-item" href="/scout/player/Fly">Fly</a>
              <a class="dropdown-item" href="/scout/player/Bang">Bang</a>
              <a class="dropdown-item" href="/scout/player/Lehends">Lehends</a>

            </div>

          </li>
        </ul>
      </div>
    </nav>